[package]
name = "serve_rs"
version = "0.1.0"
authors = ["Nathan Hare <nathanhare32@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true

[dependencies]
chrono = "0.4.11"
config = "0.10.1"